
[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    --tb=short
    --alluredir=allure-results
    --headed
markers =
    smoke: Smoke tests
    regression: Regression tests
    critical: Core functionality
    skip: Skip execution
filterwarnings =
    ignore::DeprecationWarning
